global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#vladimir_tokin'
