version: '3.3'
services:

  post_db:
    container_name: post_db
    image: mongo:latest
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db

  ui:
    image: ${USERNAME}/ui:${UI_VER}
    ports:
      - ${PORT_SRC}:${PORT_DST}/${PROTOCOL}
    networks:
      - front_net
      - prom_net

  post:
    image: ${USERNAME}/post:${POST_VER}
    networks:
      - front_net
      - back_net
      - prom_net

  comment:
    image: ${USERNAME}/comment:${COMMENT_VER}
    networks:
      - front_net
      - back_net
      - prom_net

  post_db:
  prometheus_data:

networks:
  front_net:
    external: true
  back_net:
    external: true
  prom_net:
    external: true
