---
plugin: gcp_compute
projects:
  - docker-268101
zones:
  - europe-west1-b
groups:
  app: "'reddit-docker' in name"

filters: []

hostnames:
  - name
compose:
   ansible_host: networkInterfaces[0].accessConfigs[0].natIP

auth_kind: serviceaccount
service_account_file: ~/docker-268101-2dd55859b36b.json
